DELIMITER $$ -- NAS STORED PROCEDURE É NECESSARIO USARUM DELIMITAOR DIFERENTE DO ; POIS DENTRO DE UMA STORED PROCEDURE PODEMOS TER DIVERSOS COMANDO SQL E CADA COMANDO FINALIZA COM ;

	CREATE PROCEDURE nome_procedure(IN parametro_entrada INT, OUT parametro_saida DECIMAL(10,2)) -- UMA PROCEDURE ACEITA VARIOS PARMETROS QUE PODEM SER DE ENTRADA E DE SAIDA CADA UM COM SEU TIPO ESPECIFICADO
																								 -- IN PARA ENTRADA E OUT PARA SAIDA
	
	BEGIN
		
		-- AQUI CRIAMOS TODA NOSSA LOGICA DA STORED PROCEDURE
		-- DICAS DE ESTUDOS BASICO PARA CRIAR UMA LOGICA DENTRO DAS PROCEDURES: LOOPS, CONDIÇÃO, CURSOR, VARIAVEIS
		
	END $$ -- O MOTIVO DE TERMOS ALTERADO O DELIMITADOR, JUSTAMENTE PARA ESPECIFICAR O DELIMITADOR DA PROCEDURE
	
DELIMITER ; -- VOLTAMOS O NOSSO DELIMITADOR PARA ;

CALL nome_procedure(1, @variavel_saida); -- CHMAMAMOS A PROCEDURE COM  CALL, E DEFINIMOS UMA VARIAVEL QUE IRÁ RECBER NOSSO PRAMETRO DE SAIDA

SELECT @variavel_saida;
